### ISSUE TITLE
API key expires

### ISSUE THREAD

**Issue by claireinez** [Codewars/codewars-api-docs#3]
I have been experiencing some problems using the Codewars API key; it seems to expire after about an hour meaning that I cannot make any authenticated requests until I refresh my account settings page. Once refreshed, the API key remains exactly the same and the authenticated requests are successful.

**Comment by jhoffner** [comment]
I'm adding this to the official Codewars issues list as a high priority item.

**Comment by claireinez** [comment]
Ah I see I raised this issue in the wrong place, but thanks for looking into it!
