### ISSUE TITLE
Two broken/deleted api endpoints?

### ISSUE THREAD

**Issue by the-zebulan** [Codewars/codewars-api-docs#4]
I was trying to make api calls to these two endpoints but they don't seem to be working:

* `GET completed code challenges for a given user`
    * `curl "http://www.codewars.com:3000/api/v1/users/some_user/code_challenges/completed"`
* `GET attempted code challenges for a given user`
    * `curl "http://www.codewars.com:3000/api/v1/users/some_user/code_challenges/authored"`

I tried with and without the port `3000` inside the urls but no luck either way. I'm not sure if these endpoints have just been renamed or deleted but, either way, it might be good to update the api docs.

Thanks!

**Comment by GaKSmith** [comment]
I had this problem too. I also included my access token in a header, and in the url.

**Comment by plundin** [comment]
Same problem. Response is {"success":false,"reason":"not found"}

**Comment by Dan-Nolan** [comment]
Looks like there is a typo in the code challenge routes. 

Try it without the `:3000` port and change the `code_challenges` to `code-challenges` with a dash instead.

* `GET completed code challenges for a given user`
    * `curl "http://www.codewars.com/api/v1/users/some_user/code-challenges/completed"`
* `GET attempted code challenges for a given user`
    * `curl "http://www.codewars.com/api/v1/users/some_user/code-challenges/authored"`

**Comment by the-zebulan** [comment]
@Dan-Nolan ,

Looks like you are correct about the dash VS underscore, thanks for pointing out the typo!

After changing to a dash, I tried multiple times with my Codewars username (`zebulan`) but I just kept getting an html page back with `5xx: Server Error ... ::CLOUDFLARE_ERROR_500S_BOX::` on it.

I found a random username on Codewars that had only solved 16 katas and the `completed` endpoint worked fine. I then tested a bunch of random usernames from the leaderboard and the `completed` endpoint seems to stop working ~1100 katas solved.

| Username | Katas Solved | Endpoint Worked |
| --- | --- | --- |
| ParkerLioda | 186 | :white_check_mark: |
| SquishyStrawberry | 439 | :white_check_mark: |
| ekailia | 531 | :white_check_mark: |
| jake9066 | 660 | :white_check_mark: |
| xao | 726 | :white_check_mark: |
| dkleist | 978 | :white_check_mark: |
| RichardGregoryHamilton | 1048 | :white_check_mark: |
| Dentzil | 1128 | :x: |
| ITSOES | 1254 | :x: |
| zebulan | 1395 | :x: |
| Abbe | 1786 | :x: |
| timp | 2083 | :x: |
| Unnamed | 2807 | :x: |
| myjinxin2015 | 3050 | :x: |
| St3f4n | 3296 | :x: |
| ZozoFouchtra | 3789 | :x: |
| smile67 | 3891 | :x: |

**Comment by 10XL** [comment]
@the-zebulan I've noticed the `X-Runtime` response header is consistently ~45 seconds. That seems like something is timing out.

**Comment by jhoffner** [comment]
Docs have been updated and I added pagination to the completed route. You will now need to page every 200 results.

**Comment by the-zebulan** [comment]
Ok, thanks for the update.
